### ISSUE TITLE
Module request: Brompton Tessera LED processors.

### ISSUE THREAD

**Issue by SalkinDK** [bitfocus/companion-module-brompton-tessera#1]
**Describe the feature**
be able to recall presets on the Brompton Tessera LED processors, for different mapping, colour change etc.

**Is this platform dependent (windows, mac, ..)?**
no

**If documentation is required to implement, do you know where to find it?**
https://www.bromptontech.com/support

**Usecases**
For different tile positions, colour calibration etc.

**Comment by josephdadams** [comment]
@rahilb-carallon were you planning to contribute your code here?

**Comment by rahilb-carallon** [comment]
Yes, it's not quite ready yet (I had other priorities).

**Comment by rahilb-carallon** [comment]
This is now done and a beta build is available from the downloads page
