### ISSUE TITLE
Can’t connect

### ISSUE THREAD

**Issue by kman1898** [bitfocus/companion-module-brompton-tessera#3]
On tessera remote 3.3.1 and the newest version of companion. 

I'm trying to get control of a Brompton Tessera SX40 and not having any luck. I can ping the IP address and the Tessera software connects to the processors from the same computer that Companion is running on. And Companion is able to see/control other devices in the network, so everything should be working properly.

However, when I try to connect the Tessera module to the correct IP address of our processor, it fails with an extremely long HTTP GET Request for 192.168. 10.232 failed (400. ("api" (" devices" ("items": ("00013" ('type", "DB2.6-245-V1", "00023" ("type". "DB2.6-245-V1"1 "00035" ("type" " DB2. 6-245-V1")," 00045":)

Any help is much appreciated! We're trying to connect to three total processors and I get the same error on all three of them.

The error seems to be related to the fixture pack that I’m using. The panels I’m using require a custom fixture pack. When I delete the fixture pack the error is the same but instead of “ DB2. 6-245-V1” it says “unknown”

**Comment by michaelb-bromptontech** [comment]
Hope you managed to fix this! Closing as stale for now - if you see an issue like this again don't hesitate to reach out to our support team at [https://www.bromptontech.com/support/](https://www.bromptontech.com/support/)
