### ISSUE TITLE
Request: Add Temperature step adjustment

### ISSUE THREAD

**Issue by Tedcharlesbrown** [bitfocus/companion-module-brompton-tessera#4]
Currently, only brightness step adjustment is included in this module.

request to add temperature step control.

**Comment by Tedcharlesbrown** [comment]
--> Pull request made

**Comment by CU-tony** [comment]
Would also love this feature to be added to the module

**Comment by IanTGreenwood** [comment]
I would love the ability to use variables/expressions as values.

Also, in addition to what people have said above, there are many settings i would love to have access to, such as Colour Temp, input saturation/contrast/brightness etc...

Thanks!

**Comment by michaelMVAV** [comment]
seconding the above requests for 
Colour-Tempurature, Gamma, Black Level, Contrast, Hue, Saturation

and feedback / readout for all of the above as well, Thanks!

**Comment by michaelb-bromptontech** [comment]
Closing this as temperature step has been added to the module.

Thanks for the feedback @IanTGreenwood and @michaelMVAV! I've passed it onto the team to help guide our future development. In the meantime, feel free to create seperate issues tracking features you'd like to see.
