### ISSUE TITLE
New Tessera 3.5 API changes

### ISSUE THREAD

**Issue by mjcampbell1** [bitfocus/companion-module-brompton-tessera#7]
Need to add support for the new custom test pattern layout. 
Most likely there are other API changes as well.

**Comment by harshpalan** [comment]
Yes, please. The custom test pattern doesn't work anymore

**Comment by michaelb-bromptontech** [comment]
Support for the new 3.5 endpoints has been added to the module, and will be included the upcoming v2.0.0 module release.
